const lomoCerdo = "assets/images/lomo_cerdo.jpg";
const queso = "assets/images/queso_vaca.jpg";
const sandia = "assets/images/sandia.jpg";
const pechugaPollo="assets/images/pechuga_pollo.jpg";
const pera="assets/images/pera.jpg";
const platano="assets/images/platano.jpg";
const yogurt="assets/images/yogurt.jpg";
const tomate="assets/images/tomate_rinon.jpg";
const lechuga="assets/images/lechuga.jpg";