const lomoCerdoname = "Lomo de Cerdo";
const quesoname = "Queso de Vaca";
const sandianame = "Sandía";
const pechugapolloname = "Pechuga Pollo";
const peraname = "Pera";
const platanoname = "Plátano";
const yogurtname = "Yogurt";
const lechuganame = "Lechuga";
const tomatename = "Tomate de Riñon";
